runtime: java11
instance_class: B2
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"

service: money-exchange

basic_scaling:
  max_instances: 2
  idle_timeout: 10m